apiVersion: v1
kind: Service
metadata:
  name: {{ include "djava.fullname" . }}-headless
  labels:
    app: {{ include "djava.fullname" . }}
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    app: {{ include "djava.fullname" . }}