apiVersion: v1
kind: Service
metadata:
  name: {{ include "djava.fullname" . }}-loadbalancer
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}  # External port (accessible from outside the cluster)
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ include "djava.fullname" . }}
  selector:
    app: {{ include "djava.fullname" . }}